# Generated by Django 3.2 on 2021-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210928_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='picture',
            field=models.ImageField(default='gallery/default/default.jpeg', upload_to='gallery/'),
        ),
    ]
