# Generated by Django 3.2 on 2022-04-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(default='gallery/default/default.jpeg', upload_to='gallery/'),
        ),
    ]
