# Generated by Django 3.2 on 2021-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0006_repairmanrequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='resome',
            field=models.FileField(blank=True, default='cataloges/default/default.jpeg', null=True, upload_to='resome/'),
        ),
    ]
