# Generated by Django 3.2 on 2022-04-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0009_auto_20220403_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegationrequestmodel',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairmanrequestmodel',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
