# Generated by Django 3.2 on 2021-11-27 20:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2021, 11, 28, 0, 12, 23, 151926))),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('of_superuser', models.BooleanField(default=False)),
                ('message_datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 28, 0, 12, 23, 152881))),
                ('chatsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsessionmodel')),
            ],
        ),
    ]
