# Generated by Django 3.2 on 2021-12-02 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211202_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 22, 18, 389591)),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='last_message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 22, 38, 258904)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 22, 18, 388643)),
        ),
    ]
