# Generated by Django 3.2 on 2021-12-02 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211202_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 32, 0, 354045)),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='last_message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 32, 0, 352410)),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 18, 32, 0, 352340)),
        ),
    ]
