# Generated by Django 3.2 on 2021-12-02 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20211202_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 23, 35, 13, 856154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='last_message_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 23, 35, 13, 855285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 23, 35, 13, 855240, tzinfo=utc)),
        ),
    ]
