# Generated by Django 3.2 on 2021-11-28 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_contactusmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 14, 45, 1, 3907, tzinfo=utc)),
        ),
    ]
