# Generated by Django 3.2 on 2021-12-07 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20211203_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='complained_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 32, 27, 97946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='contacted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 32, 27, 96944, tzinfo=utc)),
        ),
    ]
