# Generated by Django 3.2 on 2021-12-08 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20211207_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='complained_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 10, 20, 10, 828478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='contacted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 10, 20, 10, 827554, tzinfo=utc)),
        ),
    ]
