# Generated by Django 3.2 on 2022-03-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20211208_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='complained_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='contacted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
