# Generated by Django 3.2 on 2022-04-11 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20220318_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('phone_number', models.CharField(blank=True, max_length=264, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('does_visit_on_time', models.CharField(blank=True, max_length=264, null=True)),
                ('does_have_card', models.CharField(blank=True, max_length=264, null=True)),
                ('does_gave_tutorial', models.CharField(blank=True, max_length=264, null=True)),
                ('does_solve_problem', models.CharField(blank=True, max_length=264, null=True)),
                ('does_give_factor', models.CharField(blank=True, max_length=264, null=True)),
                ('does_announce_cost', models.CharField(blank=True, max_length=264, null=True)),
                ('does_gave_label', models.CharField(blank=True, max_length=264, null=True)),
                ('does_satisfy_you', models.CharField(blank=True, max_length=264, null=True)),
                ('number_of_visits', models.CharField(blank=True, max_length=264, null=True)),
            ],
        ),
    ]
