# Generated by Django 3.2 on 2022-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_beautiness',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_behaviour',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_cleanness',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_clothes',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_effectiveness',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='rate_overall',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='visiting_day',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
