# Generated by Django 3.2 on 2022-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220318_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingmodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
