# Generated by Django 3.2 on 2022-04-03 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderingmodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
