# Generated by Django 3.2 on 2022-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderingmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingmodel',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
