# Generated by Django 3.2 on 2022-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220318_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='size_14',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
